### ISSUE TITLE
crash: Missing feature 'session'

### ISSUE THREAD

**Issue by dchmelik** [ccooke/cccb9#5]
I'm using Slackware64 14.2 stable (with updates from today,) including ruby-2.2.8-x86_64-1_slack14.2.

d@cosmos:~/cccb9$ ./cccb9
Failed to load lib/cccb/core/session.rb: uninitialized constant CCCB::Settings
FATAL :CCCB::Core::Packages: Missing feature 'session'
["/home/d/cccb9/lib/module/requirements.rb:172:in `block in requirements'",
 "/home/d/cccb9/lib/module/requirements.rb:167:in `map'"]

**Comment by ccooke** [comment]
Curious.
I just checked a clean checkout, and it doesn't have any issues here. I assume you've installed the dependent gems in the Gemfile?

**Comment by dchmelik** [comment]
I did (after someone on IRC explained what it was.)
